# Generated by Django 5.1.6 on 2025-05-01 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional', '0001_initial'),
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_cart.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItemAdditional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional.additional')),
                ('shopping_cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_additionals', to='shopping_cart.shoppingcartitem')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='additionals',
            field=models.ManyToManyField(through='shopping_cart.ShoppingCartItemAdditional', to='additional.additional'),
        ),
    ]
