# Generated by Django 5.1.6 on 2025-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='additionals',
            field=models.ManyToManyField(blank=True, through='shopping_cart.ShoppingCartItemAdditional', to='additional.additional'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shoppingcartitemadditional',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
