# Generated by Django 5.1.6 on 2025-03-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
        ('order', '0002_remove_orderitem_additional_alter_orderitem_product_and_more'),
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='orderitemadditional',
            name='additional_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitemadditional',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.additional'),
        ),
    ]
