# Generated by Django 5.1.6 on 2025-03-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_state_alter_address_city_alter_address_name_and_more'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(blank=True, choices=[('store_pickup', 'Store Pickup'), ('delivery', 'Delivery')], max_length=20, null=True),
        ),
    ]
