# Generated by Django 5.1.6 on 2025-03-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=40),
        ),
    ]
